run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - goimports
    - ineffassign
    - typecheck
    - gocyclo
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  errcheck:
    check-type-assertions: true
    exclude-functions:
      - "w.Write"
      - "(*json.Encoder).Encode"
      - "(*json.Decoder).Decode"
  goimports:
    local-prefixes: bragdev-go

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - generated
